[package]
name = "wireofparadise/spaceship"
description = "A painless & robust data store manager for Roblox with schema versioning."
version = "1.0.0"
license = "MIT"
authors = ["wireofparadise <wireofparadise@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
homepage = "https://wireofparadise.github.io/spaceship/"
repository = "https://github.com/wireofparadise/spaceship"
exclude = [
    ".git",
    ".vscode",
    ".DS_Store",
    ".gitignore",
    "*.tgz",
    ".luaurc",
    "CONTRIBUTING.md",
    ".npmignore",
    "package-lock.json",
    "package.json",
    "*.rbxl",
    "*.rbxlx",
    "*.rbxl.lock",
    "*.rbxlx.lock",
    "*.rbxm",
    "*.rbxmx",
    "*.d.ts",
    "rokit.toml",
    "selene.toml",
    "sourcemap.json",
]
